
server:
  port: '8080'
spring:
  webflux:
    base-path: 'accounts'

auth:
  url: http://localhost:8080/accounts/api/v1/mock/auth/
consent:
  url: http://localhost:8080/accounts/api/v1/mock/consent
accounts:
  url: http://localhost:8080/accounts/api/v1/mock/accounts
accountsById:
  url: http://localhost:8080/accounts/api/v1/mock/accounts/{accountId}

#actuator
management:
  endpoint:
    health:
      show-details: ALWAYS
  health:
    ratelimiters:
      enabled: true
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:

  #rate limit
  .ratelimiter:
    configs:
      default:
        limitForPeriod: 5
        limitRefreshPeriod: 15s
        timeoutDuration: 5s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
    instances:
      accountRateLimit:
        baseConfig: default
      authRateLimit:
        baseConfig: default
      consentRateLimit:
        baseConfig: default

  #bulkhead
  bulkhead:
    configs:
      accountBulkheadConfig:
        maxConcurrentCalls: 10
        maxWaitDuration: 20s
    instances:
      accountBulkheadInstance:
        baseConfig: accountBulkheadConfig

  #circuitbreaker
  circuitbreaker:
    configs:
      accountsCircuitBreakerConfig:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 1000
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
    instances:
      authService:
        baseConfig: accountsCircuitBreakerConfig
      consentService:
        baseConfig: accountsCircuitBreakerConfig
      accountService:
        baseConfig: accountsCircuitBreakerConfig

#logging
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'
  level:
    org:
      springframework:
        web: INFO
    com:
      ob:
        tsb:
          accounts: ERROR
  file:
    name: accountsMs.log
  logback:
    rollingpolicy:
      max-history: '10'
      max-file-size: 10MB





