openapi: 3.0.0

info:
  title: Balances Microservice
  version: 0.0.1

paths:
  /api/v1/health-check:
    get:
      summary: Balance MS Health Check
      operationId: health-check
      tags:
        - balances
      responses:
        '200':
          description: Checking Balances MS Health
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
          content: { }

  /api/v1/balances:
    get:
      security:
        - jwt: []
      summary: Get balance details
      operationId: balances
      tags:
        - balances
      responses:
        '200':
          description: Balances information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/OBReadBalance'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/400'
        '401':
          description: Unauthorised access
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/403'

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/404'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/500'

  /api/v1/accounts/{AccountId}/balances:
    get:
      security:
        - jwt: []
      summary: Get balance details by Id
      operationId: balancesById
      parameters:
        - name: AccountId
          in: path
          description: Account ID
          required: true
          schema:
            type: string
      tags:
        - balances
      responses:
        '200':
          description: Balance detail by Id information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/OBReadBalance'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/400'
        '401':
          description: Unauthorised access
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/403'

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/404'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/500'





security:
  - jwt: []

components:
  securitySchemes:
    jwt:
      type: http
      in: header
      scheme: bearer
      bearerFormat: JWT
  schemas:
    401:
      type: object
      properties:
        Code:
          type: string
          default: 401 Unauthorised Access
        Id:
          type: string
          default: 2b5f0fb2-730b-11e8-adc0-fa7ae01bbebc
        Message:
          type: string
          default: Unauthorised Access
        Errors:
          type: array
          items:
            type: object
            properties:
              ErrorCode:
                type: string
                default: 401 Unauthorised
              Message:
                type: string
                default: 401 Unauthorised
              Path:
                type: string
                default: /api/v1/balance
              Url:
                type: string
                default: https://api.example.com/docs/errors/UNAUTHORISED ACCESS
    400:
      type: object
      properties:
        Code:
          type: string
          default: 400 Bad Request
        Id:
          type: string
          default: 2b5f0fb2-730b-11e8-adc0-fa7ae01bbebc
        Message:
          type: string
          default: Bad Request
        Errors:
          type: array
          items:
            type: object
            properties:
              ErrorCode:
                type: string
                default: 400 Bad Request
              Message:
                type: string
                default: 400 Bad Request
              Path:
                type: string
                default: /api/v1/balance
              Url:
                type: string
                default: https://api.example.com/docs/errors/UNAUTHORISED ACCESS
    403:
      type: object
      properties:
        Code:
          type: string
          default: 403 Forbidden
        Id:
          type: string
          default: 2b5f0fb2-730b-11e8-adc0-fa7ae01bbebc
        Message:
          type: string
          default: Forbidden
        Errors:
          type: array
          items:
            type: object
            properties:
              ErrorCode:
                type: string
                default: 403 Forbidden
              Message:
                type: string
                default: 403 Forbidden
              Path:
                type: string
                default: /api/v1/balance
              Url:
                type: string
                default: https://api.example.com/docs/errors/UNAUTHORISED ACCESS
    404:
      type: object
      properties:
        Code:
          type: string
          default: 404 Not Found
        Id:
          type: string
          default: 2b5f0fb2-730b-11e8-adc0-fa7ae01bbebc
        Message:
          type: string
          default: Forbidden
        Errors:
          type: array
          items:
            type: object
            properties:
              ErrorCode:
                type: string
                default: 404 Not Found
              Message:
                type: string
                default: 404 Not Found
              Path:
                type: string
                default: /api/v1/balance
              Url:
                type: string
                default: https://api.example.com/docs/errors/UNAUTHORISED ACCESS

    500:
      type: object
      properties:
        Code:
          type: string
          default: 500 Internal Server Error
        Id:
          type: string
          default: 2b5f0fb2-730b-11e8-adc0-fa7ae01bbebc
        Message:
          type: string
          default: Internal Server Error
        Errors:
          type: array
          items:
            type: object
            properties:
              ErrorCode:
                type: string
                default: 500 Internal Server Error
              Message:
                type: string
                default: 500 Internal Server Error
              Path:
                type: string
                default: /api/v1/balance
              Url:
                type: string
                default: https://api.example.com/docs/errors/UNAUTHORISED ACCESS

    OBReadBalance:
      type: object
      properties:
        Data:
          type: object
          properties:
            Balance:
              type: array
              items:
                type: object
                properties:
                  AccountId:
                    type: string
                  Amount:
                    type: object
                    properties:
                      Amount:
                        type: string
                      Currency:
                        type: string
                  CreditDebitIndicator:
                    type: string
                  Type:
                    type: string
                  DateTime:
                    type: string
                    format: date-time
                  CreditLine:
                    type: array
                    items:
                      type: object
                      properties:
                        Included:
                          type: boolean
                        Amount:
                          type: object
                          properties:
                            Amount:
                              type: string
                            Currency:
                              type: string
                        Type:
                          type: string
        Links:
          type: object
          properties:
            Self:
              type: string
        Meta:
          type: object
          properties:
            TotalPages:
              type: integer
              format: int32
