openapi: 3.0.0

info:
  title: Balances Microservice
  version: 0.0.1

servers:
  - url: http://localhost:8080/api
    description: Local Server

paths:
  /balances/api/v1/health-check:
    get:
      parameters:
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
        - name: x-fapi-auth-date
          in: header
          required: false
          schema:
            type: string
        - name: x-fapi-customer-ip-address
          in: header
          required: false
          schema:
            type: string
        - name: x-fapi-interaction-id
          in: header
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          required: false
          schema:
            type: string
            enum:
              - application/json
      summary: Account MS Health Check
      operationId: health-check
      tags:
        - balances
      responses:
        '200':
          description: Checking Balances MS Health
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
          content: { }

  /balances/api/v1/balances:
    get:
      summary: Get balance details
      operationId: balances
      tags:
        - balances
      responses:
        '200':
          description: Balances information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalancesResponse'

  /balances/api/v1/{AccountId}/balances:
    get:
      summary: Get balance details by id
      operationId: balanceById
      parameters:
        - name: AccountId
          in: path
          description: Account ID
          required: true
          schema:
            type: integer
            format: int64
      tags:
        - balances
      responses:
        '200':
          description: Balance information retrieved successfully by account id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceByIdResponse'


  /balances/api/v1/accounts/{AccountId}/balances:
    get:
      summary: Get balance details by Id
      operationId: balancesById
      parameters:
        - name: AccountId
          in: path
          description: Account ID
          required: true
          schema:
            type: integer
            format: int64
      tags:
        - balances
      responses:
        '200':
          description: Balance detail by Id information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceByIdResponse'

components:
  schemas:
    BalanceByIdResponse:
      type: object
      properties:
        Data:
          type: object
          properties:
            Balance:
              type: object
              properties:
                AccountId:
                  type: string
                Amount:
                  type: object
                  properties:
                    Amount:
                      type: string
                    Currency:
                      type: string
                CreditDebitIndicator:
                  type: string
                Type:
                  type: string
                DateTime:
                  type: string
                  format: date-time
                CreditLine:
                  type: array
                  items:
                    type: object
                    properties:
                      Included:
                        type: boolean
                      Amount:
                        type: object
                        properties:
                          Amount:
                            type: string
                          Currency:
                            type: string
                      Type:
                        type: string
        Links:
          type: object
          properties:
            Self:
              type: string
        Meta:
          type: object
          properties:
            TotalPages:
              type: integer
              format: int32

    BalancesResponse:
      type: object
      properties:
        Data:
          type: object
          properties:
            Balance:
              type: array
              items:
                type: object
                properties:
                  AccountId:
                    type: string
                  Amount:
                    type: object
                    properties:
                      Amount:
                        type: string
                      Currency:
                        type: string
                  CreditDebitIndicator:
                    type: string
                  Type:
                    type: string
                  DateTime:
                    type: string
                    format: date-time
                  CreditLine:
                    type: array
                    items:
                      type: object
                      properties:
                        Included:
                          type: boolean
                        Amount:
                          type: object
                          properties:
                            Amount:
                              type: string
                            Currency:
                              type: string
                        Type:
                          type: string
        Links:
          type: object
          properties:
            Self:
              type: string
        Meta:
          type: object
          properties:
            TotalPages:
              type: integer
              format: int32
