apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvs-ob-balances
  namespace: ob-sb-development-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvs-ob-balances
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        app: pvs-ob-balances
    spec:
      containers:
      - name: pvs-ob-balances
        image: "337141981580.dkr.ecr.eu-west-2.amazonaws.com/tsb_sandbox1_ecr:PVS_OB_Balances_updatesha"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ecr-pull-secret
---

apiVersion: v1
kind: Service
metadata:
  name: pvs-ob-balances
  namespace: ob-sb-development-ns
spec:
  selector:
    app: pvs-ob-balances
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
